import './globals.css'
import { Roboto } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const robot = Roboto({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'TEFA CRUD Kel.5',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robot.className}>{children}</body>
    </html>
  )
}
